### PR TITLE
Did some styling changes in the Restaurant menu page and Form.html

### LINKED ISSUE #29: errors in html files
Review thoroughly the folder of Html_css and javascript and check all the tasks have been completed. And the tasks are done as defined, if you find any errors or bugs, resolve it.

### PR DESCRIPTION
**Pull request by varunpareek690**
Hi sir
I took the plain HTML form and turned it into a captivating  that's not only visually appealing but also works smoothly on any device. I gave it a fresh look by choosing nice colors, fonts, . I have somehow made it responsive for some devices but promise to make it fully responsive!

To make it more fun, I added cool stuff. Ypu get a cool animation when you go to sign up page or return to login page

I did not stop here, I took the restaurant menu page and turned it to user-friendly menu. It's like giving your restaurant a fresh coat of paint, but on the internet. Now, people can explore the menu, drool over the pictures, and order their favorite dishes with ease. It's not just a menu; it's an experience!
I will do my best to make it appealing and complete all the tasks 
My contribution
Fixes #29 
Please find the attached screenshots of the changes I have done!
Screenshot 2023-10-05 214821

Menu Page
image

### CODE REVIEW

**Comment by UzairHussain193** [comment]
Amazing @varunpareek690, you have made a great contribution.
I encourages you to do more such contributions.

**Comment by varunpareek690** [comment]
Thank you sir, Your response is much appreciated!
It would be much useful if you could give me in the directions in which I should go, 
I am a beginner and wants to learn new things so please guide me what more I could do

**Comment by UzairHussain193** [comment]
You can connect with me on LinkedIn at https://linkedin.com/in/uzairhussain19
We will discuss there in details.

**Comment by UzairHussain193** [comment]
Hello @varunpareek690 ,

I hope this message finds you well. I wanted to take a moment to express our appreciation for your contributions to our open-source project. Your efforts have been invaluable to our community.

We have been working hard to improve and expand the project to provide more value to our users. We kindly invite you to consider showing your support by starring our repository. Starring the repository helps us grow and reach a wider audience, making it easier for others to discover and benefit from the project.

🌟 https://github.com/UzairHussain193/Get_Start_with_OpenSource_Contributions 🌟

Your star would mean a lot to us and would help us continue to make meaningful contributions to the open-source community.

Thank you for being a part of our project, and we look forward to your continued support. If you have any questions, feedback, or suggestions, please don't hesitate to reach out.

Warm regards,

Uzair Hussain
uzairhussain193@gmail.com
https://github.com/UzairHussain193/

**Pull request merged**
